# VirtualBox installation: https://www.virtualbox.org/wiki/Linux_Downloads
#
# Upon VirtualBox installation perform the following checks:
# $ which virtualbox
# /usr/bin/virtualbox
# $ virtualbox --version
# $ ps aux | grep virtualbox
---
- name: Download the Oracle PGP public key for verifying the signatures
  ansible.builtin.get_url:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    dest: "{{ oracle_asc_key_path }}"
    mode: '0664'
- name: Calculate key fingerprint
  register: output
  ansible.builtin.shell:
    cmd: gpg --with-fingerprint --show-keys {{ oracle_asc_key_path }} | sed -n '2 s/^ *//g; 2p'
- ansible.builtin.debug:
    var: output
- name: Verify the key, using a fingerprint, before import. End the play if fingerprint does not match the one provided.
  ansible.builtin.meta: end_play
  # Public key fingerprint taken from https://www.virtualbox.org/wiki/Linux_Downloads
  when: output.stdout != oracle_gpg_key_fingerprint
- name: Register the downloaded package signing key (add it to /usr/share/keyrings/)
  ansible.builtin.command:
    cmd: gpg --yes --output {{ oracle_gpg_key_path }} --dearmor {{ oracle_asc_key_path }}
  become: true
- name: Print Ubuntu distribution
  ansible.builtin.debug:
    msg: "Ubuntu distribution is: {{ ansible_distribution_release }}"
- name: Add Oracle package repo
  ansible.builtin.deb822_repository:
    architectures:
      - amd64
    enabled: true
    # /etc/apt/sources.list.d/oracle-virtualbox.sources will be created
    name: oracle-virtualbox
    types:
      - deb
    uris:
      - https://download.virtualbox.org/virtualbox/debian
    components:
      - contrib
    signed_by: "{{ oracle_gpg_key_path }}"
    suites: "{{ ansible_distribution_release }}"
  become: true
- name: Update apt cache if the last one is more than 3600 seconds ago and install VirtualBox package
  ansible.builtin.apt:
    # Package name taken from https://download.virtualbox.org/virtualbox/debian/dists/jammy/contrib/binary-amd64/Packages
    # ToDo: automate reading this information for a given distribution name.
    name: virtualbox-7.0
    update_cache: yes
    cache_valid_time: 3600
  become: true
  register: output
- ansible.builtin.debug:
    var: output
