# to remove it: 
# $ sudo dpkg --remove slack-desktop 
- name: Download Debian package
  register: output
  ansible.builtin.get_url:
    # todo: find generic url (which probably gets redirected)
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: "{{ chrome_deb_package_path }}"
- debug: var=output
# - name: Download Zoom public key
#   register: output
#   ansible.builtin.get_url:
#     url: https://zoom.us/linux/download/pubkey
#     dest: "{{ zoom_public_key_path }}"
# - debug: var=output
# - name: Verify the key, using a fingerprint, before import
#   register: output
#   ansible.builtin.rpm_key:
#     key: "{{ zoom_public_key_path }}"
#     # taken from https://zoom.us/download?os=linux
#     fingerprint: 3960 60CA DD8A 7522 0BFC B369 B903 BF18 61A7 C71D
# - debug: var=output
- name: Install Chrome's .deb package
  register: output
  become: true
  ansible.builtin.apt:
    deb: "{{ chrome_deb_package_path }}"
- debug: var=output
- name: Cleanup
  ansible.builtin.file:
    path: "{{ chrome_deb_package_path }}"
    state: absent