---
- name: Download the Hashicorp PGP public key for verifying the signatures
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "{{ hashicorp_asc_key_path }}"
    mode: '0664'
- name: Register the downloaded package signing key (add it to /usr/share/keyrings/)
  ansible.builtin.command:
    cmd: gpg --yes --output {{ hashicorp_gpg_key_path }} --dearmor {{ hashicorp_asc_key_path }}
  become: true
  changed_when: true
- name: Add Hashicorp package repo
  ansible.builtin.deb822_repository:
    architectures:
      - amd64
    enabled: true
    # /etc/apt/sources.list.d/hashicorp.sources will be created
    name: hashicorp
    types:
      - deb
    uris:
      - https://apt.releases.hashicorp.com
    components:
      - main
    signed_by: "{{ hashicorp_gpg_key_path }}"
    suites: "{{ ansible_distribution_release }}"
  become: true
- name: Update apt cache if the last one is more than 3600 seconds ago and install terraform package
  ansible.builtin.apt:
    # Package name taken from https://download.virtualbox.org/virtualbox/debian/dists/jammy/contrib/binary-amd64/Packages
    # ToDo: automate reading this information for a given distribution name.
    name: terraform
    update_cache: true
    cache_valid_time: 3600
  become: true
  register: output
- name: Print command output
  ansible.builtin.debug:
    var: output
- name: Verify Terraform version
  ansible.builtin.command:
    cmd: terraform version
  register: output
- name: Print output
  ansible.builtin.debug:
    var: output
