---
- name: Print all facts
  ansible.builtin.debug:
    var: ansible_facts
- name: Print fact
  ansible.builtin.debug:
    msg: "{{ fact }} = {{ ansible_facts[fact] }}"
  # fact can be used as ansible_facts key only if its name does not start with ansible_
  when: fact is not match ('ansible_')
- name: Print fact
  ansible.builtin.debug:
    var: '{{ fact }}'
  # fact can be used as standalone variable only if its name starts with ansible_
  when: fact is match ('ansible_')
