- name: Update and upgrade apt packages
  become: true
  register: output
  ansible.builtin.apt:
    name: "*"
    state: latest
    cache_valid_time: 86400 # seconds in 1 day
- debug: var=output
- name: Install a list of packages
  become: true
  register: output
  ansible.builtin.apt:
    pkg:
    - rpm
- debug: var=output