- name: check ownership of /dev/kvm
  register: output
  ansible.builtin.command: 
    cmd: ls -al /dev/kvm
- debug: var=output.stdout
- name: Add your (non-root) user to the kvm group in order to access the kvm device
  register: output
  become: yes
  ansible.builtin.command: 
    # $USER is root if become:yes
    # cmd: usermod -aG kvm $USER
    cmd: usermod -aG kvm {{ non_root_user }}
- debug: var=output.stdout
- name: Verify that (non-root) user is in kvm group
  register: output
  become: yes
  ansible.builtin.command: 
    cmd: groups {{ non_root_user }}
- debug: var=output.stdout
- name: Install required apt packages
  become: yes
  register: output
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- debug: var=output.stdout
- name: create APT keyring directory
  register: output
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
- debug: var=output.stdout
- name: Add Docker’s official GPG key
  become: yes
  register: output
  # "curl: option --dearmor: is unknown"
  # ansible.builtin.command: 
  #   cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  # apt_key:
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
- debug: var=output.stdout
- name: set up the repository
  register: output
  ansible.builtin.command: 
    cmd: >
      echo
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- debug: var=output
- name: download latest Deb package 
  register: output
  ansible.builtin.get_url:
    url: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.12.0-amd64.deb
    dest: "{{ desktop_docker_deb_package_path }}"
- debug: var=output.stdout
- name: Install deb package
  register: output
  ansible.builtin.apt:
    deb: "{{ desktop_docker_deb_package_path }}"

