#  https://ubuntu.com/blog/kvm-hyphervisor
---
- name: Install KVM on Ubuntu
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install the required packages
      become: true
      ansible.builtin.apt:
        name:
          - bridge-utils
          - cpu-checker
          - libvirt-clients
          - libvirt-daemon
          - qemu
          - qemu-kvm
      register: apt_output
    - name: Print apt output
      ansible.builtin.debug:
        var: apt_output
    - name: Check virtualisation capabilities
      ansible.builtin.command:
        cmd: kvm-ok
      register: kvmok_output
    - name: Print kvm-ok output
      ansible.builtin.debug:
        var: kvmok_output
    # todo: Report success if the output contains these lines:
    #       INFO: /dev/kvm exists
    #       KVM acceleration can be used
