#
# TODO: check if VSCode is installed and if so, its current version.
# Compare that version with the version available and only if newer is available
# then download and install the newer version.
#
# https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
# returns 302 redirect code and redirects to urls similar to:
# https://az764295.vo.msecnd.net/stable/74b1f979648cc44d385a2286793c226e611f59e7/code_1.71.2-1663191218_amd64.deb
#
- name: Download VSCode Debian package
  register: output
  ansible.builtin.get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: "{{ vscode_deb_package_path }}"
    mode: '0440'
- name: Print output
  ansible.builtin.debug:
    var: output
- name: Install VSCode's .deb package
  register: output
  become: true
  ansible.builtin.apt:
    deb: "{{ vscode_deb_package_path }}"
- name: Print output
  ansible.builtin.debug:
    var: output
- name: Cleanup
  ansible.builtin.file:
    path: "{{ vscode_deb_package_path }}"
    state: absent
- name: Verify VSCode version
  ansible.builtin.command:
    cmd: code --version
  register: output
- name: Print output
  ansible.builtin.debug:
    var: output
